/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "var(--surface)",
        'surface-dim': "var(--surface-dim)",
        'surface-bright': "var(--surface-bright)",
        'surface-container-lowest': "var(--surface-container-lowest)",
        'surface-container-low': "var(--surface-container-low)",
        'surface-container': "var(--surface-container)",
        'surface-container-high': "var(--surface-container-high)",
        'surface-container-highest': "var(--surface-container-highest)",
        'on-surface': "var(--on-surface)",
        'on-surface-variant': "var(--on-surface-variant)",
        'inverse-surface': "var(--inverse-surface)",
        'inverse-on-surface': "var(--inverse-on-surface)",
        outline: "var(--outline)",
        'outline-variant': "var(--outline-variant)",
        'surface-tint': "var(--surface-tint)",
        primary: "var(--primary)",
        'on-primary': "var(--on-primary)",
        'primary-container': "var(--primary-container)",
        'on-primary-container': "var(--on-primary-container)",
        'inverse-primary': "var(--inverse-primary)",
        secondary: "var(--secondary)",
        'on-secondary': "var(--on-secondary)",
        'secondary-container': "var(--secondary-container)",
        'on-secondary-container': "var(--on-secondary-container)",
        tertiary: "var(--tertiary)",
        'on-tertiary': "var(--on-tertiary)",
        'tertiary-container': "var(--tertiary-container)",
        'on-tertiary-container': "var(--on-tertiary-container)",
        border: "var(--outline-variant)",
        accent: {
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "monospace"],
      },
      boxShadow: {
        glow: "0 0 0 1px rgba(255,255,255,0.06), 0 20px 60px rgba(0,0,0,0.55)",
        glowStrong: "0 0 0 1px rgba(255,255,255,0.08), 0 30px 90px rgba(0,0,0,0.6)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
